export {
  // Multi-server: qualified session-id helpers
  LOCAL_SERVER_ID,
  parseSessionRef,
  formatSessionRef,
  normalizeSessionRef,
  type SessionRef,
  // REST: POST /api/sessions
  CreateSessionRequestSchema,
  CreateSessionResponseSchema,
  type CreateSessionRequest,
  type CreateSessionResponse,
  // REST: GET /api/sessions
  SessionInfoSchema,
  ListSessionsResponseSchema,
  ScrollbackResponseSchema,
  GitStatusResponseSchema,
  type SessionInfo,
  type ListSessionsResponse,
  type ScrollbackResponse,
  type GitStatusResponse,
  // REST: File Explorer /api/sessions/:id/fs/*
  FsEntryTypeSchema,
  FsEntrySchema,
  FsListResponseSchema,
  FsReadResponseSchema,
  FsMkdirRequestSchema,
  FsMkdirResponseSchema,
  FsRenameRequestSchema,
  FsRenameResponseSchema,
  FsDeleteResponseSchema,
  FsUploadResponseSchema,
  type FsEntryType,
  type FsEntry,
  type FsListResponse,
  type FsReadResponse,
  type FsMkdirRequest,
  type FsMkdirResponse,
  type FsRenameRequest,
  type FsRenameResponse,
  type FsDeleteResponse,
  type FsUploadResponse,
  // REST: PATCH /api/sessions/:id
  UpdateSessionRequestSchema,
  UpdateSessionResponseSchema,
  type UpdateSessionRequest,
  type UpdateSessionResponse,
  // Multi-server: server registry
  ServerIdSchema,
  ServerTypeSchema,
  ServerReachabilitySchema,
  ServerAuthMethodSchema,
  ServerInfoSchema,
  ListServersResponseSchema,
  CreateServerRequestSchema,
  CreateServerResponseSchema,
  TestServerRequestSchema,
  TestServerResponseSchema,
  type ServerId,
  type ServerType,
  type ServerReachability,
  type ServerAuthMethod,
  type ServerInfo,
  type ListServersResponse,
  type CreateServerRequest,
  type CreateServerResponse,
  type TestServerRequest,
  type TestServerResponse,
  // REST: errors
  ApiErrorSchema,
  type ApiError,
  // WS: client -> server
  WsResizeSchema,
  WsPingSchema,
  WsClientMessageSchema,
  type WsResize,
  type WsPing,
  type WsClientMessage,
  // WS: server -> client
  WsExitSchema,
  WsPongSchema,
  WsErrorSchema,
  WsServerMessageSchema,
  type WsExit,
  type WsPong,
  type WsError,
  type WsServerMessage,
} from "./terminal";
export {
  // REST: GET /api/sessions/:id/screen
  ScreenResponseSchema,
  type ScreenResponse,
  // REST: POST /api/sessions/:id/keys
  AgentNamedKeySchema,
  SendKeysRequestSchema,
  type AgentNamedKey,
  type SendKeysRequest,
  // Agent chat WS: client -> server
  AgentUserMessageSchema,
  AgentApprovalBehaviorSchema,
  AgentApprovalResponseSchema,
  AgentInterruptSchema,
  AgentPingSchema,
  AgentListChatsSchema,
  AgentDeleteChatSchema,
  AgentWsClientMessageSchema,
  type AgentUserMessage,
  type AgentApprovalBehavior,
  type AgentApprovalResponse,
  type AgentInterrupt,
  type AgentPing,
  type AgentListChats,
  type AgentDeleteChat,
  type AgentWsClientMessage,
  // Agent chat WS: server -> client
  AgentChatStartedSchema,
  AgentAssistantDeltaSchema,
  AgentAssistantMessageSchema,
  AgentToolUseSchema,
  AgentToolResultSchema,
  AgentApprovalRequestSchema,
  AgentStatusStateSchema,
  AgentStatusSchema,
  AgentErrorSchema,
  AgentPongSchema,
  AgentChatSummarySchema,
  AgentChatListSchema,
  AgentReplayEntrySchema,
  AgentChatHistorySchema,
  AgentWsServerMessageSchema,
  type AgentChatStarted,
  type AgentAssistantDelta,
  type AgentAssistantMessage,
  type AgentToolUse,
  type AgentToolResult,
  type AgentApprovalRequest,
  type AgentStatusState,
  type AgentStatus,
  type AgentError,
  type AgentPong,
  type AgentChatSummary,
  type AgentChatList,
  type AgentReplayEntry,
  type AgentChatHistory,
  type AgentWsServerMessage,
} from "./agent";
export {
  LoginBodySchema,
  AuthErrorSchema,
  MeResponseSchema,
  WS_CLOSE_UNAUTHORIZED,
  type LoginBody,
  type AuthError,
  type MeResponse,
} from "./auth";
