// Web terminal gateway (Phase 3: origin allowlist, user/pass auth, bind config, limits).
//
// The gateway NEVER owns the job. tmux owns it. On WS attach we spawn a
// node-pty running `tmux attach-session`; on WS close we kill ONLY that pty,
// which detaches the tmux client. The tmux session and its child jobs keep
// running. The tmux session-terminating call appears in EXACTLY ONE place in
// this file: the DELETE /api/sessions/:id handler — the single intentional,
// user-confirmed job kill. Every tmux operation (list/attach/create/delete) is filtered to the
// `web-` name prefix so the gateway can never see or touch unrelated sessions.
import http from "node:http";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import crypto from "node:crypto";
import { fileURLToPath } from "node:url";
import { execFile, spawn } from "node:child_process";
import { promisify } from "node:util";
import { WebSocketServer } from "ws";
import { spawn as ptySpawn } from "node-pty";
import metadata from "./metadata.js";
import registry from "./registry.js";
import push from "./push.js";
import { hashPassword, isValidHashString, verifyPassword } from "./password.js";

const execFileAsync = promisify(execFile);
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PUBLIC_DIR = path.join(__dirname, "..", "public");
const PORT = Number(process.env.PORT) || 3007;
const HOST = process.env.HOST || "127.0.0.1";

// ---- A3: Security + deployment configuration ----
// Credentials: a single user/password pair from env (no user store, no DB).
// Production sets GATEWAY_AUTH_PASSWORD_HASH (generated by `pnpm --filter
// @sparklab/terminal-gateway hash-password`); GATEWAY_AUTH_PASSWORD (plain)
// is a dev/test convenience, hashed at startup.
const GATEWAY_AUTH_USER = process.env.GATEWAY_AUTH_USER || "";
const GATEWAY_AUTH_PASSWORD_HASH = process.env.GATEWAY_AUTH_PASSWORD_HASH || "";
const GATEWAY_AUTH_PASSWORD = process.env.GATEWAY_AUTH_PASSWORD || "";
const TRUST_PROXY = process.env.TRUST_PROXY === "1";
const ALLOWED_ORIGINS_RAW =
  process.env.ALLOWED_ORIGINS || "http://localhost:3000,http://localhost:3007";
const ALLOWED_ORIGINS = new Set(
  ALLOWED_ORIGINS_RAW.split(",")
    .map((s) => s.trim())
    .filter(Boolean),
);
const MAX_WS_CONNECTIONS = Number(process.env.MAX_WS_CONNECTIONS) || 32;

// The pre-user/pass shared secret is gone. Refusing to start (rather than
// ignoring the var) keeps an un-migrated deploy from silently coming up with
// auth disabled behind its proxy.
if (process.env.GATEWAY_AUTH_TOKEN) {
  console.error(
    "[gateway] FATAL: GATEWAY_AUTH_TOKEN is no longer supported. Set GATEWAY_AUTH_USER and GATEWAY_AUTH_PASSWORD_HASH instead",
  );
  console.error(
    "[gateway] (generate the hash with: pnpm --filter @sparklab/terminal-gateway hash-password).",
  );
  process.exit(1);
}

// Open mode: auth fully disabled when no credentials are set AND host is
// loopback. No credentials + non-loopback HOST is a configuration error —
// refuse to start. Partial credentials are always a configuration error.
const LOOPBACK_HOSTS = new Set(["127.0.0.1", "::1", "localhost"]);
const OPEN_MODE =
  !GATEWAY_AUTH_USER && !GATEWAY_AUTH_PASSWORD_HASH && !GATEWAY_AUTH_PASSWORD;
if (!OPEN_MODE) {
  const missing = !GATEWAY_AUTH_USER
    ? "GATEWAY_AUTH_USER"
    : !GATEWAY_AUTH_PASSWORD_HASH && !GATEWAY_AUTH_PASSWORD
      ? "GATEWAY_AUTH_PASSWORD_HASH (or GATEWAY_AUTH_PASSWORD)"
      : null;
  if (missing) {
    console.error(
      `[gateway] FATAL: partial auth configuration — ${missing} is not set.`,
    );
    process.exit(1);
  }
  if (
    GATEWAY_AUTH_PASSWORD_HASH &&
    !isValidHashString(GATEWAY_AUTH_PASSWORD_HASH)
  ) {
    console.error(
      "[gateway] FATAL: GATEWAY_AUTH_PASSWORD_HASH is not a valid scrypt hash string.",
    );
    console.error(
      "[gateway] Generate one with: pnpm --filter @sparklab/terminal-gateway hash-password",
    );
    process.exit(1);
  }
  if (GATEWAY_AUTH_PASSWORD_HASH && GATEWAY_AUTH_PASSWORD) {
    console.warn(
      "[gateway] WARNING: both GATEWAY_AUTH_PASSWORD_HASH and GATEWAY_AUTH_PASSWORD are set; using the hash.",
    );
  }
}
// The one hash every login verifies against. Plaintext env (dev) is hashed
// once at startup so the login path is identical in both configurations.
const AUTH_PASSWORD_HASH = OPEN_MODE
  ? ""
  : GATEWAY_AUTH_PASSWORD_HASH || hashPassword(GATEWAY_AUTH_PASSWORD);
if (OPEN_MODE && !LOOPBACK_HOSTS.has(HOST)) {
  console.error(
    `[gateway] FATAL: no auth credentials are set but HOST="${HOST}" is not a loopback address.`,
  );
  console.error(
    "[gateway] Either set GATEWAY_AUTH_USER + GATEWAY_AUTH_PASSWORD_HASH or bind to a loopback address (127.0.0.1, ::1, localhost).",
  );
  process.exit(1);
}
if (OPEN_MODE) {
  console.warn(
    "[gateway] WARNING: running in open mode (no auth). Ensure gateway is accessible from trusted hosts only.",
  );
}

// ---- A2: Auth sessions (in-memory, 30-day absolute expiry) ----
const AUTH_SESSION_TTL_MS = 30 * 24 * 60 * 60 * 1000;
const authSessions = new Map(); // sid -> { expires: number, username: string }

function createAuthSession(username) {
  const sid = crypto.randomBytes(16).toString("hex");
  authSessions.set(sid, {
    expires: Date.now() + AUTH_SESSION_TTL_MS,
    username,
  });
  return sid;
}

// Returns the live session record, or null.
function getAuthSession(sid) {
  if (!sid) return null;
  const session = authSessions.get(sid);
  if (!session) return null;
  if (session.expires < Date.now()) {
    authSessions.delete(sid);
    return null;
  }
  return session;
}

function validateAuthSession(sid) {
  return getAuthSession(sid) !== null;
}

// ---- Cookie helpers ----
function parseCookies(req) {
  const cookies = {};
  const header = req.headers.cookie || "";
  for (const part of header.split(";")) {
    const idx = part.indexOf("=");
    if (idx < 0) continue;
    const k = part.slice(0, idx).trim();
    const v = part.slice(idx + 1).trim();
    if (k) cookies[k] = v;
  }
  return cookies;
}

function buildSessionCookie(sid) {
  let cookie = `gw_session=${sid}; HttpOnly; SameSite=Strict; Path=/`;
  if (TRUST_PROXY) cookie += "; Secure";
  return cookie;
}

function clearSessionCookie() {
  return "gw_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0";
}

// ---- Auth middleware ----
// Returns true when the request is authenticated (or in open mode).
function isAuthenticated(req) {
  if (OPEN_MODE) return true;
  const cookies = parseCookies(req);
  return validateAuthSession(cookies.gw_session);
}

// ---- A1: Origin helpers ----
// In open mode (loopback-only dev), origin enforcement is skipped so that
// non-browser clients (test scripts using the `ws` library, curl) can connect
// without a browser-set Origin header.  In auth mode the origin MUST be in the
// allowlist — absent counts as disallowed.
function isOriginAllowed(origin) {
  if (OPEN_MODE) return true; // no enforcement in open mode
  if (!origin) return false;
  return ALLOWED_ORIGINS.has(origin);
}

// ---- A4: Rate limiting for /api/auth/login ----
const loginAttempts = new Map(); // ip -> { count: number, windowStart: number }
const LOGIN_WINDOW_MS = 60_000;
const LOGIN_MAX_ATTEMPTS = 5;

function getClientIp(req) {
  if (TRUST_PROXY) {
    const xff = req.headers["x-forwarded-for"];
    if (xff) return xff.split(",")[0].trim();
  }
  return req.socket.remoteAddress || "0.0.0.0";
}

function checkLoginRateLimit(ip) {
  const now = Date.now();
  const record = loginAttempts.get(ip);
  if (!record || now - record.windowStart >= LOGIN_WINDOW_MS) {
    loginAttempts.set(ip, { count: 1, windowStart: now });
    return { allowed: true };
  }
  record.count++;
  if (record.count > LOGIN_MAX_ATTEMPTS) {
    const retryAfter = Math.ceil(
      (record.windowStart + LOGIN_WINDOW_MS - now) / 1000,
    );
    return { allowed: false, retryAfter };
  }
  return { allowed: true };
}

// ---- SHA-256 helper for timing-safe token compare ----
function sha256buf(str) {
  return crypto.createHash("sha256").update(str).digest();
}

const PREFIX = "web-";
// Session ids must be web- prefixed and contain only hyphen-safe chars. This
// rejects hostile/typo path params before they ever reach tmux.
const ID_RE = /^web-[A-Za-z0-9-]+$/;

// Named keys accepted by POST /api/sessions/:id/keys. Whitelist-only: every
// item is passed to `tmux send-keys` WITHOUT -l, so anything not listed here
// is rejected with 400 before it can reach tmux. Mirrors AgentNamedKeySchema
// in @sparklab/shared-types (packages/shared-types/src/agent.ts) — keep the
// two in sync. Duplicated as a plain Set so the gateway stays dependency-free.
const AGENT_NAMED_KEYS = new Set([
  "Enter",
  "Escape",
  "Tab",
  "Space",
  "BSpace",
  "Up",
  "Down",
  "Left",
  "Right",
  "Home",
  "End",
  "PageUp",
  "PageDown",
  "DC",
  "C-c",
  "C-d",
  "C-z",
  "C-l",
  "C-u",
  "C-r",
]);
// text ≤ this length AND single-line goes through `send-keys -l`; anything
// longer or multiline goes through load-buffer/paste-buffer (bracketed paste).
const SEND_KEYS_LITERAL_MAX = 200;
const SEND_TEXT_MAX = 10_000;

const MIME = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".map": "application/json; charset=utf-8",
  ".svg": "image/svg+xml; charset=utf-8",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
};

// ---------------------------------------------------------------------------
// Multi-server ("Connected Servers"): qualified session ids + the exec seam.
// ---------------------------------------------------------------------------
// Canonical parse/format lives in packages/shared-types/src/terminal.ts
// (parseSessionRef / formatSessionRef / LOCAL_SERVER_ID). The gateway is plain
// dependency-free JS and CANNOT import that module at runtime (same reason it
// duplicates AGENT_NAMED_KEYS), so we mirror the exact split/join here — KEEP
// THE TWO IN SYNC.
const LOCAL_SERVER_ID = "local";

// Split on the FIRST "/": before => serverId, after => tmux name. No "/" means
// a bare tmux name (old bookmark / single-server client) => serverId "local".
function parseSessionRef(ref) {
  const slash = ref.indexOf("/");
  if (slash < 0) return { serverId: LOCAL_SERVER_ID, tmuxName: ref };
  return {
    serverId: ref.slice(0, slash) || LOCAL_SERVER_ID,
    tmuxName: ref.slice(slash + 1),
  };
}

// Always emit the canonical qualified form (even for "local") so the target
// host is never implicit anywhere on the wire.
function formatSessionRef(serverId, tmuxName) {
  return `${serverId || LOCAL_SERVER_ID}/${tmuxName}`;
}

// One control socket per server so every control exec AND the WS attach reuse a
// single TCP+auth handshake (ControlMaster). Kept short to stay under the
// ~104-char unix-socket path limit.
const SSH_CONTROL_DIR = path.join(os.tmpdir(), "gw-ssh-cm");
try {
  fs.mkdirSync(SSH_CONTROL_DIR, { recursive: true, mode: 0o700 });
} catch {}

// Password auth (opt-in per server) uses OpenSSH's askpass helper rather than a
// prompt: SSH_ASKPASS_REQUIRE=force (OpenSSH >= 8.4) makes ssh read the password
// from this helper even without a controlling terminal AND even when node-pty
// gives the attach a pty — so both exec seams work non-interactively. The helper
// echoes $GW_SSH_PASSWORD, which we pass via the child env (NOT argv), so the
// secret never appears in `ps`. Key-based servers never touch any of this.
const SSH_ASKPASS_PATH = path.join(SSH_CONTROL_DIR, "askpass.sh");
try {
  fs.writeFileSync(
    SSH_ASKPASS_PATH,
    "#!/bin/sh\nprintf '%s\\n' \"$GW_SSH_PASSWORD\"\n",
    { mode: 0o700 },
  );
} catch {}

function sshHost(server) {
  return server.user ? `${server.user}@${server.host}` : server.host;
}

// Extra child-process env for a server. For password auth, wire the askpass
// helper + force it + pass the secret by env (never argv). Empty for local and
// key-based servers, so their spawn env is unchanged.
function sshEnvFor(server) {
  if (server && server.type === "ssh" && server.password) {
    return {
      SSH_ASKPASS: SSH_ASKPASS_PATH,
      SSH_ASKPASS_REQUIRE: "force",
      GW_SSH_PASSWORD: server.password,
    };
  }
  return {};
}

// Merge process.env with the server's extra ssh env. Only allocates a new object
// when there's something to add.
function childEnvFor(server) {
  const extra = sshEnvFor(server);
  return Object.keys(extra).length ? { ...process.env, ...extra } : process.env;
}

// Shared ssh options for BOTH control execs and the reachability probe. Two
// modes: key-based (BatchMode=yes => ssh never prompts) or password (askpass;
// pubkey disabled so we go straight to the password, single attempt).
function sshOptsFor(server) {
  const usePassword = !!(server && server.password);
  const opts = [
    "-o",
    usePassword ? "BatchMode=no" : "BatchMode=yes",
    "-o",
    "StrictHostKeyChecking=accept-new",
    "-o",
    "ConnectTimeout=8",
    "-o",
    "ServerAliveInterval=15",
    "-o",
    "ControlMaster=auto",
    "-o",
    `ControlPath=${path.join(SSH_CONTROL_DIR, "cm-%r@%h:%p")}`,
    "-o",
    "ControlPersist=60s",
  ];
  if (usePassword) {
    // Go straight to password auth in one attempt; the control socket then
    // carries every later exec/attach so the password is only used on connect.
    opts.push(
      "-o",
      "PreferredAuthentications=password",
      "-o",
      "PubkeyAuthentication=no",
      "-o",
      "NumberOfPasswordPrompts=1",
    );
  }
  if (server.port) opts.push("-p", String(server.port));
  if (!usePassword && server.identityFile) {
    opts.push("-i", server.identityFile, "-o", "IdentitiesOnly=yes");
  }
  return opts;
}

// POSIX single-quote an argument for the REMOTE shell. Wrap in single quotes
// and escape any embedded single quote as '\''. Only needed on the ssh path.
function shellQuote(arg) {
  return `'${String(arg).replace(/'/g, "'\\''")}'`;
}

// THE EXEC SEAM. Returns argv for execFile/ptySpawn running `tmux <tmuxArgs>`
// either locally or over ssh. For type:"local" it returns the bare tmux argv —
// ZERO behavior change for the single-server path. `tty:true` forces ssh to
// allocate a pty (the WS-attach seam needs `ssh -tt … tmux attach-session`).
// `server.tmuxCommand` (file-only config, e.g. ["tmux","-L","sock"]) overrides
// the tmux invocation so a test/advanced setup can target a separate socket.
//
// Local vs remote quoting: locally we execFile tmux directly (no shell), so each
// argv element is already one literal argument. Over ssh, the remote sshd runs
// the command through a shell that RE-SPLITS on whitespace and interprets
// metacharacters — so a `-F "#{a}\t#{b}"` format (spaces/tabs), a `send-keys`
// text arg, or a cwd path with spaces would break. We therefore shell-quote
// every token into a single remote command string so the remote tmux receives
// the exact same argv it would locally.
function serverExecArgv(server, tmuxArgs, { tty = false } = {}) {
  const tmuxCmd =
    Array.isArray(server && server.tmuxCommand) && server.tmuxCommand.length
      ? server.tmuxCommand
      : ["tmux"];
  if (!server || server.type === "local") {
    return [...tmuxCmd, ...tmuxArgs];
  }
  const argv = ["ssh"];
  if (tty) argv.push("-tt");
  const remoteCmd = [...tmuxCmd, ...tmuxArgs].map(shellQuote).join(" ");
  argv.push(...sshOptsFor(server), sshHost(server), remoteCmd);
  return argv;
}

// Control-seam exec: run tmux on `server`, await stdout/stderr.
async function serverExec(server, tmuxArgs) {
  const argv = serverExecArgv(server, tmuxArgs);
  return execFileAsync(argv[0], argv.slice(1), { env: childEnvFor(server) });
}

// Control-seam exec with `input` piped to stdin (used by `load-buffer -`).
// promisified execFile exposes the underlying ChildProcess as `.child`; the
// input flows through the ssh child exactly as it did through the tmux child.
async function serverExecStdin(server, tmuxArgs, input) {
  const argv = serverExecArgv(server, tmuxArgs);
  const promise = execFileAsync(argv[0], argv.slice(1), {
    env: childEnvFor(server),
  });
  promise.child.stdin.end(input);
  return promise;
}

// ---------------------------------------------------------------------------
// Non-tmux exec seam: serverCmdArgv / serverCmd / serverCmdStdin
// ---------------------------------------------------------------------------
// Identical to serverExecArgv/serverExec/serverExecStdin but WITHOUT the tmux
// prefix — they run an ARBITRARY argv (find/head/cat/mkdir/mv/rm/tee) locally
// or over ssh. Used by the File Explorer fs/* routes. Same quoting contract:
// locally we execFile argv[0] directly (no shell, each element one literal
// argument); over ssh the remote sshd re-splits on whitespace, so every token
// is shellQuote'd into one remote command string. Reuse childEnvFor so the
// password-auth askpass env is present. Callers MUST pass paths as a single
// argv element and terminate options with `--`; never concatenate a path into
// a command string.

// Default child maxBuffer: the fs listing (up to ~5000 entries) and a 256 KB
// read must fit. execFile's default is only 1 MB.
const FS_CMD_MAX_BUFFER = 16 * 1024 * 1024;
const FS_CMD_TIMEOUT_MS = 15_000;

function serverCmdArgv(server, argv, { tty = false } = {}) {
  if (!server || server.type === "local") {
    return argv;
  }
  const ssh = ["ssh"];
  if (tty) ssh.push("-tt");
  const remoteCmd = argv.map(shellQuote).join(" ");
  ssh.push(...sshOptsFor(server), sshHost(server), remoteCmd);
  return ssh;
}

// Run an arbitrary argv on `server`, await stdout/stderr. Mirrors serverExec.
async function serverCmd(server, argv, opts = {}) {
  const a = serverCmdArgv(server, argv);
  return execFileAsync(a[0], a.slice(1), {
    env: childEnvFor(server),
    timeout: FS_CMD_TIMEOUT_MS,
    maxBuffer: FS_CMD_MAX_BUFFER,
    ...opts,
  });
}

// Run an arbitrary argv on `server` with `input` piped to stdin. Mirrors
// serverExecStdin; used by fs/upload (`tee -- <dest>`). `input` is a Buffer or
// string already buffered under the route-local upload cap.
async function serverCmdStdin(server, argv, input, opts = {}) {
  const a = serverCmdArgv(server, argv);
  const promise = execFileAsync(a[0], a.slice(1), {
    env: childEnvFor(server),
    timeout: FS_CMD_TIMEOUT_MS,
    maxBuffer: FS_CMD_MAX_BUFFER,
    ...opts,
  });
  promise.child.stdin.end(input);
  return promise;
}

// ---- Cached reachability probe (`ssh <host> true`) ----
// The 3 s session poll and GET /api/servers must not fire a fresh ssh probe per
// server per tick, so results are cached with a short TTL. "local" is always
// "ok" (no ssh). "unreachable" means "couldn't ask" — never "dead".
const REACHABILITY_TTL_MS = 12_000;
const reachabilityCache = new Map(); // serverId -> { reachability, lastProbeAt, at }

async function probeServer(server, { force = false } = {}) {
  if (!server || server.type === "local") {
    return { reachability: "ok", lastProbeAt: null };
  }
  const cached = reachabilityCache.get(server.id);
  if (!force && cached && Date.now() - cached.at < REACHABILITY_TTL_MS) {
    return {
      reachability: cached.reachability,
      lastProbeAt: cached.lastProbeAt,
    };
  }
  let reachability = "unreachable";
  let error;
  try {
    const argv = ["ssh", ...sshOptsFor(server), sshHost(server), "true"];
    await execFileAsync(argv[0], argv.slice(1), {
      timeout: 10_000,
      env: childEnvFor(server),
    });
    reachability = "ok";
  } catch (err) {
    error = String(err.stderr || err.message || "")
      .trim()
      .slice(0, 300);
  }
  const lastProbeAt = Date.now();
  reachabilityCache.set(server.id, {
    reachability,
    lastProbeAt,
    at: lastProbeAt,
  });
  return { reachability, lastProbeAt, error };
}

async function sessionExists(server, name) {
  if (!ID_RE.test(name)) return false;
  try {
    await serverExec(server, ["has-session", "-t", name]);
    return true;
  } catch {
    return false;
  }
}

// Create + configure a new session on `server`. This is the only path that
// spawns a tmux session; attach never creates. Options mirror Phase 1.
async function createSession(server, id, cwd) {
  const args = ["new-session", "-d", "-s", id];
  if (cwd) args.push("-c", cwd);
  await serverExec(server, args);
  await serverExec(server, [
    "set-option",
    "-t",
    id,
    "history-limit",
    "50000",
  ]).catch((e) => console.warn(`[tmux] history-limit failed: ${e.message}`));
  // status off is a server-global nicety; scope with -g and swallow errors.
  await serverExec(server, ["set-option", "-g", "status", "off"]).catch((e) =>
    console.warn(`[tmux] status off failed: ${e.message}`),
  );
  // Prefer the most recently active client's size when multiple viewers attach.
  await serverExec(server, [
    "set-option",
    "-t",
    id,
    "window-size",
    "latest",
  ]).catch(() => {});
  await serverExec(server, [
    "set-option",
    "-t",
    id,
    "aggressive-resize",
    "on",
  ]).catch(() => {});
  console.log(`[tmux] created session "${id}" on server "${server.id}"`);
}

// List only web- prefixed sessions across ALL registered servers, joined with
// metadata. Per-server error-isolated: one dead host must NEVER fail the whole
// list. A reachable server contributes live `tmux ls` rows (reachable:true); an
// UNREACHABLE server contributes last-known rows reconstructed from the sidecar
// (reachable:false) — never omitted, never pruned.
async function listSessions() {
  const servers = registry.list();
  const meta = metadata.list();
  const sessions = [];
  const liveIds = [];
  const reachableServerIds = new Set();

  await Promise.all(
    servers.map(async (server) => {
      let out = "";
      let ok = false;
      try {
        const res = await serverExec(server, [
          "list-sessions",
          "-F",
          "#{session_name}\t#{session_created}\t#{pane_current_command}\t#{session_attached}\t#{session_activity}",
        ]);
        out = res.stdout;
        ok = true;
      } catch (err) {
        // Local: "no server running" is normal => reachable with zero sessions.
        // ssh: a failure means the host couldn't be reached this tick.
        if (server.type === "local") {
          ok = true;
          out = "";
        } else {
          ok = false;
          console.warn(
            `[api] list on server "${server.id}" failed: ${err.message}`,
          );
        }
      }
      if (!ok) return; // unreachable: reconstructed from the sidecar below
      reachableServerIds.add(server.id);
      for (const line of out.split("\n")) {
        if (!line.trim()) continue;
        const [name, created, currentCommand, attached, activity] =
          line.split("\t");
        if (!name || !name.startsWith(PREFIX)) continue;
        const qid = formatSessionRef(server.id, name);
        liveIds.push(qid);
        const m = meta[qid] || {};
        sessions.push({
          id: qid,
          name: m.name || name,
          createdAt: m.createdAt || (created ? Number(created) * 1000 : null),
          tags: m.tags || [],
          currentCommand: currentCommand || "",
          attached: Number(attached) > 0,
          attachedClients: Number(attached) || 0,
          lastActivity: activity ? Number(activity) : null,
          org: m.org ?? null,
          project: m.project ?? null,
          serverId: server.id,
          reachable: true,
        });
      }
    }),
  );

  // Reconstruct last-known rows for every registered server that did NOT
  // respond this tick, from the metadata sidecar. reachable:false, and the
  // unknowable fields are nulled/emptied (the FE greys off `reachable`).
  for (const server of servers) {
    if (reachableServerIds.has(server.id)) continue;
    for (const [qid, m] of Object.entries(meta)) {
      const { serverId, tmuxName } = parseSessionRef(qid);
      if (serverId !== server.id) continue;
      if (!tmuxName.startsWith(PREFIX)) continue;
      sessions.push({
        id: qid,
        name: m.name || tmuxName,
        createdAt: m.createdAt || null,
        tags: m.tags || [],
        currentCommand: "",
        attached: false,
        attachedClients: 0,
        lastActivity: null,
        org: m.org ?? null,
        project: m.project ?? null,
        serverId: server.id,
        reachable: false,
      });
    }
  }

  // Prune metadata ONLY within the servers that actually responded, so an
  // unreachable server's last-known metadata is preserved as the cache.
  metadata.pruneToExisting(liveIds, reachableServerIds);
  return sessions;
}

// ---------------------------------------------------------------------------
// Push "job finished" poll loop
// ---------------------------------------------------------------------------
//
// The ONLY new always-on architectural change, and it is fully inert unless
// there is ≥1 push subscription AND VAPID is configured: the loop is started
// when the first subscription arrives and stopped when the last leaves, so
// zero subscriptions => zero cost, zero behavior change (identical single-
// server / remote-SSH profile to before this feature).
//
// Signal: a session's `pane_current_command` (already returned per-session by
// listSessions()) transitioning from a real non-shell command to a shell. NO
// screen-diffing — list-sessions gives currentCommand cheaply in one call.
//
// Baseline: the FIRST tick after a (re)start records every session's current
// command and notifies nothing — otherwise every already-running job would
// "finish" on gateway restart and spam. Per-session last-known state is
// in-memory/transient (jobs survive; notifications are best-effort).

// Login shells arrive as "bash"/"zsh" or, for a login shell, "-bash"/"-zsh".
// Mirrors the SHELLS set the agent-service uses (apps/agent-service/src/tools.ts).
const SHELLS = new Set(["bash", "zsh", "fish", "sh", "dash"]);
const PUSH_POLL_INTERVAL_MS = 4000;

let pushPollTimer = null;
let pushLastCommand = new Map(); // qid -> last-known currentCommand (reachable rows only)
let pushBaselinePending = true;

function isShellCommand(cmd) {
  if (!cmd) return false; // "" is UNKNOWN, never a shell, never a trigger
  const base = cmd.startsWith("-") ? cmd.slice(1) : cmd; // login-shell "-bash"
  return SHELLS.has(base);
}

async function pushPollTick() {
  if (!push.isConfigured() || push.count() === 0) return;
  let sessions;
  try {
    sessions = await listSessions();
  } catch (err) {
    console.warn(`[push] poll list failed: ${err.message}`);
    return;
  }
  const finished = [];
  const seen = new Set();
  for (const s of sessions) {
    // Only reachable rows carry a real currentCommand. Unreachable rows return
    // a fabricated "" — letting that overwrite state would fire spurious pushes
    // on flap (job -> "" -> job). Skip them entirely => a flap is a no-op.
    if (!s.reachable) continue;
    seen.add(s.id);
    const prev = pushLastCommand.get(s.id);
    const curr = s.currentCommand || "";
    // Fire only when a session KNOWN at/after baseline goes from a genuine
    // non-shell command to a shell. New sessions (no prior entry) just seed.
    if (!pushBaselinePending && prev !== undefined) {
      if (prev && !isShellCommand(prev) && isShellCommand(curr)) {
        finished.push(s);
      }
    }
    pushLastCommand.set(s.id, curr);
  }
  // Forget sessions that vanished so a re-created id re-baselines cleanly.
  for (const id of [...pushLastCommand.keys()]) {
    if (!seen.has(id)) pushLastCommand.delete(id);
  }
  pushBaselinePending = false;

  for (const s of finished) {
    // Payload transits FCM/Apple/Mozilla push services — keep it GENERIC:
    // session name + "finished", NEVER command output.
    const payload = {
      title: "Job finished",
      body: `${s.name}: the running command finished.`,
      sessionId: s.id,
      tag: `job-${s.id}`,
    };
    console.log(
      `[push] job finished in "${s.id}" -> notifying ${push.count()} subscription(s)`,
    );
    void push
      .sendToAll(payload)
      .catch((err) => console.warn(`[push] sendToAll failed: ${err.message}`));
  }
}

// Start the loop (idempotent). Resets baseline state so stopped->running always
// re-baselines; a 2nd subscription while already running is a no-op (no
// re-baseline). Called on subscribe and at boot when subscriptions persist.
function startPushLoop() {
  if (pushPollTimer) return;
  if (!push.isConfigured() || push.count() === 0) return;
  pushLastCommand = new Map();
  pushBaselinePending = true;
  pushPollTimer = setInterval(() => void pushPollTick(), PUSH_POLL_INTERVAL_MS);
  if (pushPollTimer.unref) pushPollTimer.unref();
  console.log("[push] job-finished poll loop started");
}

// Stop the loop and clear state so a future start re-baselines from scratch.
function stopPushLoop() {
  if (!pushPollTimer) return;
  clearInterval(pushPollTimer);
  pushPollTimer = null;
  pushLastCommand = new Map();
  pushBaselinePending = true;
  console.log("[push] job-finished poll loop stopped");
}

// ---- JSON helpers ----
function sendJson(res, code, obj) {
  const body = JSON.stringify(obj);
  res.writeHead(code, { "content-type": "application/json; charset=utf-8" });
  res.end(body);
}

// A4: 64 KB body cap.
const BODY_LIMIT = 65_536;

function readBody(req) {
  return new Promise((resolve, reject) => {
    let data = "";
    req.on("data", (chunk) => {
      data += chunk;
      if (data.length > BODY_LIMIT) {
        const err = new Error("body too large");
        err.code = "BODY_TOO_LARGE";
        reject(err);
        req.destroy();
      }
    });
    req.on("end", () => resolve(data));
    req.on("error", reject);
  });
}

// ---- File Explorer (fs/*) helpers ----
// Read cap for text preview (bytes). Binary/oversized files are downloaded.
const FS_READ_CAP = 256 * 1024;
// Max directory entries returned before `truncated:true`.
const FS_LIST_CAP = 5000;
// Route-local upload cap (bytes). This is SEPARATE from the 64 KB BODY_LIMIT —
// only the fs/upload route bypasses BODY_LIMIT, and only up to this cap.
const FS_UPLOAD_CAP = 8 * 1024 * 1024;
// Hard stop for a hung download stream.
const FS_DOWNLOAD_TIMEOUT_MS = 120_000;

// A path arg must be a non-empty absolute string. This is the user's own shell
// (full-fs access is the feature); we only require absolute for predictability.
function isAbsPath(p) {
  return typeof p === "string" && p.length > 0 && p.startsWith("/");
}

// Map a child-process error (execFile rejection) to an HTTP status by sniffing
// stderr/message. permission -> 403, missing/not-a-dir -> 404, exists/not-empty
// -> 409, everything else -> 502.
function fsErrorStatus(err) {
  const s = String((err && (err.stderr || err.message)) || "").toLowerCase();
  if (/permission denied|operation not permitted/.test(s)) return 403;
  if (/not empty|file exists|already exists|exists/.test(s)) return 409;
  if (/no such file|not found|not a directory|cannot stat/.test(s)) return 404;
  return 502;
}

// A short, sanitized single-line message from a child error's stderr.
function fsErrorMessage(err, fallback) {
  const raw = String((err && err.stderr) || "").trim();
  if (!raw) return fallback;
  const line = raw.split("\n")[0].trim();
  return line || fallback;
}

// find's %y type char -> our FsEntry type.
function fsTypeOf(y) {
  if (y === "d") return "dir";
  if (y === "f") return "file";
  if (y === "l") return "symlink";
  return "other";
}

// The current type of a single path via `find <path> -maxdepth 0 -printf '%y'`.
// Returns the type char ('d'/'f'/'l'/...) or throws (mapped to 404/403/502).
async function fsStatType(server, p) {
  const { stdout } = await serverCmd(server, [
    "find",
    p,
    "-maxdepth",
    "0",
    "-printf",
    "%y",
  ]);
  return stdout.trim();
}

// Parse `git status --porcelain=v2 --branch` output into the footer summary.
// v2 headers are `# branch.<key> <value>`; entry lines start with 1/2/u/?/!.
// For 1 & 2 lines the XY field is two chars: X = index/staged, Y = worktree/
// unstaged; '.' means unchanged. `changed` counts DISTINCT files (each entry
// line once); the per-bucket counts may overlap (a file both staged & unstaged
// increments both). Matches the classification used by shell git prompts.
function parseGitPorcelain(out) {
  let branch = null;
  let detached = false;
  let oid = null;
  let ahead = 0;
  let behind = 0;
  let staged = 0;
  let unstaged = 0;
  let untracked = 0;
  let conflicted = 0;
  let changed = 0;

  for (const line of out.split("\n")) {
    if (!line) continue;
    if (line.startsWith("# ")) {
      const rest = line.slice(2);
      if (rest.startsWith("branch.oid ")) {
        oid = rest.slice("branch.oid ".length).trim();
      } else if (rest.startsWith("branch.head ")) {
        const v = rest.slice("branch.head ".length).trim();
        if (v === "(detached)") detached = true;
        else branch = v;
      } else if (rest.startsWith("branch.ab ")) {
        const m = /\+(-?\d+)\s+-(-?\d+)/.exec(rest);
        if (m) {
          ahead = Number(m[1]) || 0;
          behind = Number(m[2]) || 0;
        }
      }
      continue;
    }
    const kind = line[0];
    if (kind === "1" || kind === "2") {
      const xy = line.slice(2, 4);
      if (xy[0] && xy[0] !== ".") staged++;
      if (xy[1] && xy[1] !== ".") unstaged++;
      changed++;
    } else if (kind === "u") {
      conflicted++;
      changed++;
    } else if (kind === "?") {
      untracked++;
      changed++;
    }
    // '!' (ignored) lines aren't emitted without --ignored; skip if present.
  }

  // Detached HEAD: no branch name — surface the short oid instead.
  if (detached && !branch && oid && oid !== "(initial)") {
    branch = oid.slice(0, 7);
  }

  return {
    isRepo: true,
    branch,
    detached,
    ahead,
    behind,
    staged,
    unstaged,
    untracked,
    conflicted,
    changed,
  };
}

// The exact guard chain every /api/sessions/:id/* route runs. Sends the 404 and
// returns null on any miss; returns { server, tmuxName } on success.
async function fsResolveSession(res, rawRef) {
  const { serverId, tmuxName } = parseSessionRef(decodeURIComponent(rawRef));
  if (!ID_RE.test(tmuxName)) {
    sendJson(res, 404, { error: "session not found" });
    return null;
  }
  const server = registry.get(serverId);
  if (!server) {
    sendJson(res, 404, { error: "session not found" });
    return null;
  }
  if (!(await sessionExists(server, tmuxName))) {
    sendJson(res, 404, { error: "session not found" });
    return null;
  }
  return { server, tmuxName };
}

// ---- A2: Auth route handlers ----
async function handleLogin(req, res) {
  const ip = getClientIp(req);
  const rateCheck = checkLoginRateLimit(ip);
  if (!rateCheck.allowed) {
    res.writeHead(429, {
      "content-type": "application/json; charset=utf-8",
      "retry-after": String(rateCheck.retryAfter),
    });
    res.end(
      JSON.stringify({
        error: "too many attempts",
        retryAfter: rateCheck.retryAfter,
      }),
    );
    return;
  }

  let body = {};
  try {
    const raw = await readBody(req);
    if (raw.trim()) body = JSON.parse(raw);
  } catch (err) {
    if (err.code === "BODY_TOO_LARGE") {
      res.writeHead(413, { "content-type": "application/json; charset=utf-8" });
      res.end(JSON.stringify({ error: "request too large" }));
      return;
    }
    return sendJson(res, 400, { error: "malformed JSON body" });
  }

  if (typeof body.username !== "string" || typeof body.password !== "string") {
    return sendJson(res, 400, { error: "username and password are required" });
  }

  // Timing-safe: hash both usernames to equal length before comparing, and
  // ALWAYS run the full password verification (no short-circuit on a wrong
  // username), so response time never leaks which field was wrong.
  const userOk = crypto.timingSafeEqual(
    sha256buf(GATEWAY_AUTH_USER),
    sha256buf(body.username),
  );
  const passOk = verifyPassword(body.password, AUTH_PASSWORD_HASH);

  if (!userOk || !passOk) {
    return sendJson(res, 401, { error: "invalid credentials" });
  }

  const sid = createAuthSession(GATEWAY_AUTH_USER);
  res.writeHead(204, { "set-cookie": buildSessionCookie(sid) });
  res.end();
}

async function handleLogout(req, res) {
  const cookies = parseCookies(req);
  if (cookies.gw_session) {
    authSessions.delete(cookies.gw_session);
  }
  res.writeHead(204, { "set-cookie": clearSessionCookie() });
  res.end();
}

function handleMe(req, res) {
  // Open mode: authenticated, but deliberately WITHOUT a username — its
  // absence is how the frontend detects open mode (and hides Sign out).
  if (OPEN_MODE) {
    return sendJson(res, 200, { authenticated: true });
  }
  const session = getAuthSession(parseCookies(req).gw_session);
  if (session) {
    return sendJson(res, 200, {
      authenticated: true,
      username: session.username,
    });
  }
  return sendJson(res, 401, { error: "unauthorized" });
}

// ---- Org/project validation ----
// Shared by POST /api/sessions and PATCH /api/sessions/:id.
// Returns { ok: true, value: trimmedString } or { ok: false, error: string }.
function validateGroupField(raw, fieldName) {
  if (raw === null) return { ok: true, value: null };
  if (typeof raw !== "string")
    return { ok: false, error: `${fieldName} must be a string` };
  const trimmed = raw.trim();
  if (trimmed.length < 1 || trimmed.length > 32) {
    return {
      ok: false,
      error: `${fieldName} must be 1-32 characters after trimming`,
    };
  }
  if (trimmed.includes("/")) {
    return { ok: false, error: `${fieldName} must not contain "/"` };
  }
  return { ok: true, value: trimmed };
}

// ---- Server registry validation ----
// Mirrors CreateServerRequestSchema in @sparklab/shared-types. `type` is forced
// to "ssh" — "local" is pre-registered and cannot be added. Key-based by default;
// an optional `password` enables ssh password auth. Returns { ok, entry } or
// { ok:false, error }.
const SERVER_ID_RE = /^[A-Za-z0-9][A-Za-z0-9_-]{0,63}$/;
function validateServerBody(body) {
  if (typeof body.id !== "string" || !SERVER_ID_RE.test(body.id)) {
    return {
      ok: false,
      error: 'server id must be alphanumeric with - or _ (no "/"), 1-64 chars',
    };
  }
  if (body.id === "local") {
    return { ok: false, error: '"local" is reserved' };
  }
  if (
    typeof body.name !== "string" ||
    body.name.trim().length < 1 ||
    body.name.length > 64
  ) {
    return { ok: false, error: "name must be 1-64 characters" };
  }
  if (typeof body.host !== "string" || body.host.trim().length < 1) {
    return { ok: false, error: "host is required" };
  }
  const entry = {
    id: body.id,
    name: body.name.trim(),
    type: "ssh",
    host: body.host.trim(),
  };
  if (body.user != null) {
    if (typeof body.user !== "string") {
      return { ok: false, error: "user must be a string" };
    }
    if (body.user.trim()) entry.user = body.user.trim();
  }
  if (body.port != null) {
    if (
      typeof body.port !== "number" ||
      !Number.isInteger(body.port) ||
      body.port < 1 ||
      body.port > 65535
    ) {
      return { ok: false, error: "port must be an integer 1..65535" };
    }
    entry.port = body.port;
  }
  if (body.identityFile != null) {
    if (typeof body.identityFile !== "string") {
      return { ok: false, error: "identityFile must be a string" };
    }
    if (body.identityFile.trim()) entry.identityFile = body.identityFile.trim();
  }
  // Optional password auth. Stored (plaintext) in the gitignored servers.json;
  // never returned over the API (serverInfoOf omits it). When present it takes
  // precedence over identityFile (sshOptsFor switches to password auth).
  if (body.password != null) {
    if (typeof body.password !== "string") {
      return { ok: false, error: "password must be a string" };
    }
    if (body.password.length) entry.password = body.password;
  }
  return { ok: true, entry };
}

// Shape a registry record into the GET /api/servers wire form (ServerInfo).
// `identityFile` is deliberately omitted (no MVP edit UI). No password exists.
function serverInfoOf(server, probe) {
  const info = {
    id: server.id,
    name: server.name,
    type: server.type,
    reachability: probe.reachability,
    lastProbeAt: probe.lastProbeAt ?? null,
  };
  if (server.type === "ssh") {
    info.host = server.host;
    if (server.user) info.user = server.user;
    info.port = server.port ?? 22;
    // How this server authenticates — NEVER the password value itself.
    info.authMethod = server.password ? "password" : "key";
  }
  return info;
}

// ---- REST API ----
// Returns true if it handled the request.
async function handleApi(req, res, url) {
  const parts = url.pathname.split("/").filter(Boolean); // ['api', 'auth'|'sessions', ...]

  // A1: Origin check for state-changing REST when Origin header is present (CSRF guard).
  if (
    (req.method === "POST" ||
      req.method === "DELETE" ||
      req.method === "PATCH") &&
    req.headers.origin
  ) {
    if (!isOriginAllowed(req.headers.origin)) {
      return sendJson(res, 403, { error: "forbidden origin" });
    }
  }

  // A2: Auth routes — no session cookie required.
  if (parts[1] === "auth") {
    if (req.method === "POST" && parts[2] === "login") {
      await handleLogin(req, res);
      return true;
    }
    if (req.method === "POST" && parts[2] === "logout") {
      await handleLogout(req, res);
      return true;
    }
    if (req.method === "GET" && parts[2] === "me") {
      handleMe(req, res);
      return true;
    }
    sendJson(res, 404, { error: "not found" });
    return true;
  }

  // A2: All other /api/* routes require a valid session (or open mode).
  if (!isAuthenticated(req)) {
    return sendJson(res, 401, { error: "unauthorized" });
  }

  // ---- Web Push: /api/push/* ----

  // GET /api/push/vapid-public-key — the client needs this to subscribe. When
  // push is not configured server-side (no VAPID keys), `configured:false` and
  // no key: the client disables the toggle rather than crashing. GET => exempt
  // from the Origin check (like scrollback/screen/git).
  if (
    req.method === "GET" &&
    parts.length === 3 &&
    parts[1] === "push" &&
    parts[2] === "vapid-public-key"
  ) {
    const publicKey = push.getPublicKey();
    return sendJson(res, 200, {
      configured: push.isConfigured(),
      ...(publicKey ? { publicKey } : {}),
    });
  }

  // POST /api/push/subscribe — store a browser PushSubscription. State-changing
  // => the Origin/CSRF check above already fired for this method.
  if (
    req.method === "POST" &&
    parts.length === 3 &&
    parts[1] === "push" &&
    parts[2] === "subscribe"
  ) {
    if (!push.isConfigured()) {
      return sendJson(res, 503, { error: "push not configured" });
    }
    let body = {};
    try {
      const raw = await readBody(req);
      if (raw.trim()) body = JSON.parse(raw);
    } catch (err) {
      if (err.code === "BODY_TOO_LARGE") {
        res.writeHead(413, {
          "content-type": "application/json; charset=utf-8",
        });
        res.end(JSON.stringify({ error: "request too large" }));
        return true;
      }
      return sendJson(res, 400, { error: "malformed JSON body" });
    }
    // Hand-validate the subscription shape (gateway is dependency-free; mirrors
    // PushSubscribeRequestSchema in @sparklab/shared-types).
    if (
      !body ||
      typeof body.endpoint !== "string" ||
      !/^https?:\/\//.test(body.endpoint) ||
      !body.keys ||
      typeof body.keys.p256dh !== "string" ||
      !body.keys.p256dh ||
      typeof body.keys.auth !== "string" ||
      !body.keys.auth
    ) {
      return sendJson(res, 400, { error: "invalid push subscription" });
    }
    let cnt;
    try {
      cnt = push.add({
        endpoint: body.endpoint,
        expirationTime: body.expirationTime ?? null,
        keys: { p256dh: body.keys.p256dh, auth: body.keys.auth },
      });
    } catch (err) {
      return sendJson(res, 400, { error: err.message });
    }
    // Starting the loop is idempotent; the first subscription boots it.
    startPushLoop();
    return sendJson(res, 201, { ok: true, count: cnt });
  }

  // POST /api/push/unsubscribe — drop a subscription by endpoint. Idempotent.
  if (
    req.method === "POST" &&
    parts.length === 3 &&
    parts[1] === "push" &&
    parts[2] === "unsubscribe"
  ) {
    let body = {};
    try {
      const raw = await readBody(req);
      if (raw.trim()) body = JSON.parse(raw);
    } catch (err) {
      if (err.code === "BODY_TOO_LARGE") {
        res.writeHead(413, {
          "content-type": "application/json; charset=utf-8",
        });
        res.end(JSON.stringify({ error: "request too large" }));
        return true;
      }
      return sendJson(res, 400, { error: "malformed JSON body" });
    }
    if (!body || typeof body.endpoint !== "string" || !body.endpoint) {
      return sendJson(res, 400, { error: "endpoint is required" });
    }
    push.remove(body.endpoint);
    // Last subscription gone => stop the loop (back to zero cost).
    if (push.count() === 0) stopPushLoop();
    return sendJson(res, 200, { ok: true, count: push.count() });
  }

  // ---- Multi-server: /api/servers ----

  // GET /api/servers — registry + cached reachability probe. local always first.
  if (req.method === "GET" && parts.length === 2 && parts[1] === "servers") {
    const servers = registry.list();
    const out = await Promise.all(
      servers.map(async (s) => serverInfoOf(s, await probeServer(s))),
    );
    return sendJson(res, 200, out);
  }

  // POST /api/servers/test  — probe WITHOUT saving (add-dialog "Test connection")
  // POST /api/servers/:id/test — probe an already-saved server
  if (
    req.method === "POST" &&
    parts[1] === "servers" &&
    ((parts.length === 3 && parts[2] === "test") ||
      (parts.length === 4 && parts[3] === "test"))
  ) {
    // /:id/test — look up the saved server.
    if (parts.length === 4) {
      const id = decodeURIComponent(parts[2]);
      const server = registry.get(id);
      if (!server) return sendJson(res, 404, { error: "server not found" });
      const probe = await probeServer(server, { force: true });
      return sendJson(res, 200, {
        reachability: probe.reachability,
        ...(probe.error ? { error: probe.error } : {}),
      });
    }
    // /test — probe ad-hoc params (not persisted).
    let body = {};
    try {
      const raw = await readBody(req);
      if (raw.trim()) body = JSON.parse(raw);
      if (body === null || typeof body !== "object" || Array.isArray(body)) {
        return sendJson(res, 400, { error: "body must be a JSON object" });
      }
    } catch (err) {
      if (err.code === "BODY_TOO_LARGE") {
        res.writeHead(413, {
          "content-type": "application/json; charset=utf-8",
        });
        res.end(JSON.stringify({ error: "request too large" }));
        return true;
      }
      return sendJson(res, 400, { error: "malformed JSON body" });
    }
    const v = validateServerBody(body);
    if (!v.ok) return sendJson(res, 400, { error: v.error });
    const probe = await probeServer(v.entry, { force: true });
    // Do not pollute the cache with an unsaved server id.
    reachabilityCache.delete(v.entry.id);
    return sendJson(res, 200, {
      reachability: probe.reachability,
      ...(probe.error ? { error: probe.error } : {}),
    });
  }

  // POST /api/servers — register an ssh server.
  if (req.method === "POST" && parts.length === 2 && parts[1] === "servers") {
    let body = {};
    try {
      const raw = await readBody(req);
      if (raw.trim()) body = JSON.parse(raw);
      if (body === null || typeof body !== "object" || Array.isArray(body)) {
        return sendJson(res, 400, { error: "body must be a JSON object" });
      }
    } catch (err) {
      if (err.code === "BODY_TOO_LARGE") {
        res.writeHead(413, {
          "content-type": "application/json; charset=utf-8",
        });
        res.end(JSON.stringify({ error: "request too large" }));
        return true;
      }
      return sendJson(res, 400, { error: "malformed JSON body" });
    }
    const v = validateServerBody(body);
    if (!v.ok) return sendJson(res, 400, { error: v.error });
    if (registry.get(v.entry.id)) {
      return sendJson(res, 400, { error: "server id already exists" });
    }
    let stored;
    try {
      stored = registry.add(v.entry);
    } catch (err) {
      return sendJson(res, 400, { error: err.message });
    }
    const probe = await probeServer(stored, { force: true });
    return sendJson(res, 201, serverInfoOf(stored, probe));
  }

  // DELETE /api/servers/:id — 204. "local" is undeletable (400).
  if (req.method === "DELETE" && parts.length === 3 && parts[1] === "servers") {
    const id = decodeURIComponent(parts[2]);
    if (id === "local") {
      return sendJson(res, 400, { error: '"local" cannot be deleted' });
    }
    if (!registry.get(id)) {
      return sendJson(res, 404, { error: "server not found" });
    }
    registry.remove(id);
    reachabilityCache.delete(id);
    console.log(`[api] deleted server "${id}"`);
    res.writeHead(204);
    res.end();
    return true;
  }

  // POST /api/sessions
  if (req.method === "POST" && parts.length === 2 && parts[1] === "sessions") {
    let body = {};
    try {
      const raw = await readBody(req);
      if (raw.trim()) body = JSON.parse(raw);
      if (body === null || typeof body !== "object" || Array.isArray(body)) {
        return sendJson(res, 400, { error: "body must be a JSON object" });
      }
    } catch (err) {
      if (err.code === "BODY_TOO_LARGE") {
        res.writeHead(413, {
          "content-type": "application/json; charset=utf-8",
        });
        res.end(JSON.stringify({ error: "request too large" }));
        return true;
      }
      return sendJson(res, 400, { error: "malformed JSON body" });
    }

    let cwd;
    if (body.cwd != null) {
      if (typeof body.cwd !== "string") {
        return sendJson(res, 400, { error: "cwd must be a string" });
      }
      try {
        if (!fs.statSync(body.cwd).isDirectory()) {
          return sendJson(res, 400, { error: "cwd is not a directory" });
        }
        cwd = body.cwd;
      } catch {
        return sendJson(res, 400, { error: "cwd does not exist" });
      }
    }

    if (body.name != null && typeof body.name !== "string") {
      return sendJson(res, 400, { error: "name must be a string" });
    }

    // Org/project validation (both optional on create).
    let org = null;
    let project = null;
    if (body.org != null) {
      const v = validateGroupField(body.org, "org");
      if (!v.ok) return sendJson(res, 400, { error: v.error });
      org = v.value;
    }
    if (body.project != null) {
      const v = validateGroupField(body.project, "project");
      if (!v.ok) return sendJson(res, 400, { error: v.error });
      project = v.value;
    }
    if (project && !org) {
      return sendJson(res, 400, { error: "project requires org" });
    }

    // Target server: absent/omitted => "local" (backward-compatible).
    const serverId =
      body.serverId != null ? String(body.serverId) : LOCAL_SERVER_ID;
    if (body.serverId != null && typeof body.serverId !== "string") {
      return sendJson(res, 400, { error: "serverId must be a string" });
    }
    const server = registry.get(serverId);
    if (!server) {
      return sendJson(res, 400, { error: `unknown server "${serverId}"` });
    }

    // crypto.randomUUID() is already hyphen-safe (no dots/colons).
    const tmuxName = `${PREFIX}${crypto.randomUUID()}`;
    const id = formatSessionRef(serverId, tmuxName);
    try {
      await createSession(server, tmuxName, cwd);
    } catch (err) {
      console.error(`[api] create failed: ${err.message}`);
      return sendJson(res, 500, {
        error: `failed to create session: ${err.message}`,
      });
    }
    const createdAt = Date.now();
    const name = body.name || tmuxName;
    metadata.upsert(id, { name, createdAt, org, project });
    return sendJson(res, 201, { id, name, createdAt, org, project, serverId });
  }

  // GET /api/sessions
  if (req.method === "GET" && parts.length === 2 && parts[1] === "sessions") {
    try {
      const sessions = await listSessions();
      return sendJson(res, 200, sessions);
    } catch (err) {
      console.error(`[api] list failed: ${err.message}`);
      return sendJson(res, 500, { error: "failed to list sessions" });
    }
  }

  // GET /api/sessions/:id/scrollback
  // B1: Read-only scrollback capture via tmux capture-pane.
  // Auth required (handled above). GET is exempt from Origin check.
  if (
    req.method === "GET" &&
    parts.length === 4 &&
    parts[1] === "sessions" &&
    parts[3] === "scrollback"
  ) {
    const { serverId, tmuxName } = parseSessionRef(
      decodeURIComponent(parts[2]),
    );
    if (!ID_RE.test(tmuxName)) {
      return sendJson(res, 404, { error: "session not found" });
    }
    const server = registry.get(serverId);
    if (!server) {
      return sendJson(res, 404, { error: "session not found" });
    }
    if (!(await sessionExists(server, tmuxName))) {
      return sendJson(res, 404, { error: "session not found" });
    }
    // Parse lines param: integer 1..10000, default 2000.
    const rawLines = url.searchParams.get("lines");
    let lines = 2000;
    if (rawLines !== null) {
      const parsed = parseInt(rawLines, 10);
      if (Number.isFinite(parsed)) {
        lines = Math.min(10000, Math.max(1, parsed));
      }
      // If not a valid integer, fall back to default 2000.
    }
    try {
      // -p: stdout  -e: ANSI escapes  -J: join wrapped lines
      // -S -<N>: start N lines back  -E -1: stop before last visible line
      const result = await serverExec(server, [
        "capture-pane",
        "-p",
        "-e",
        "-J",
        "-S",
        `-${lines}`,
        "-E",
        "-1",
        "-t",
        tmuxName,
      ]);
      return sendJson(res, 200, { lines: result.stdout });
    } catch (err) {
      console.error(`[api] scrollback failed: ${err.message}`);
      return sendJson(res, 500, { error: "failed to capture scrollback" });
    }
  }

  // GET /api/sessions/:id/git
  // Read-only VCS summary for the session's current working directory: branch,
  // upstream ahead/behind, and staged/unstaged/untracked/conflicted file counts.
  // Scoped to the ACTIVE session only (the mini footer) — deliberately NOT part
  // of GET /api/sessions, which would run `git status` for every session on
  // every server every 3s. GET is exempt from the Origin check (like scrollback
  // /screen). Runs one `git status --porcelain=v2 --branch` through the non-tmux
  // exec seam (local or ssh, reusing the ControlMaster socket).
  if (
    req.method === "GET" &&
    parts.length === 4 &&
    parts[1] === "sessions" &&
    parts[3] === "git"
  ) {
    const s = await fsResolveSession(res, parts[2]);
    if (!s) return true;
    const { server, tmuxName } = s;

    // Resolve the session's cwd (same mechanism as fs/list).
    let dir;
    try {
      const r = await serverExec(server, [
        "display-message",
        "-p",
        "-t",
        tmuxName,
        "#{pane_current_path}",
      ]);
      dir = r.stdout.trim();
    } catch (err) {
      console.error(`[api] git cwd failed: ${err.message}`);
      return sendJson(res, 502, { error: "failed to resolve session cwd" });
    }
    if (!isAbsPath(dir)) {
      return sendJson(res, 502, { error: "failed to resolve session cwd" });
    }

    let out;
    try {
      // `dir` flows as a single argv token (never concatenated). 8s timeout so
      // a slow/huge repo can't stall the 5s footer poll indefinitely.
      const r = await serverCmd(
        server,
        ["git", "-C", dir, "status", "--porcelain=v2", "--branch"],
        { timeout: 8000 },
      );
      out = r.stdout;
    } catch (err) {
      const stderr = String(err.stderr || err.message || "");
      // Exit 128 with this message => the cwd isn't inside a git work tree.
      // Render nothing (isRepo:false), not an error badge.
      if (/not a git repository/i.test(stderr)) {
        return sendJson(res, 200, { isRepo: false });
      }
      console.error(`[api] git status failed: ${err.message}`);
      return sendJson(res, 502, { error: "failed to read git status" });
    }

    return sendJson(res, 200, parseGitPorcelain(out));
  }

  // =========================================================================
  // File Explorer — /api/sessions/:id/fs/*
  // Each route runs the standard guard chain (parseSessionRef -> ID_RE ->
  // registry.get -> sessionExists, all 404) via fsResolveSession. GET routes
  // are Origin-exempt (like scrollback/screen); POST/PATCH/DELETE inherit the
  // Origin check applied at the top of handleApi. Every path flows into the
  // exec seam as ONE argv element and every command terminates options with
  // `--`; no path is ever concatenated into a command string.
  // =========================================================================

  // GET /api/sessions/:id/fs/list?path=<abs>&showHidden=0
  if (
    req.method === "GET" &&
    parts.length === 5 &&
    parts[1] === "sessions" &&
    parts[3] === "fs" &&
    parts[4] === "list"
  ) {
    const s = await fsResolveSession(res, parts[2]);
    if (!s) return true;
    const { server, tmuxName } = s;

    // Omitted path -> resolve the session's current working directory.
    let dir = url.searchParams.get("path");
    if (dir === null || dir === "") {
      try {
        const r = await serverExec(server, [
          "display-message",
          "-p",
          "-t",
          tmuxName,
          "#{pane_current_path}",
        ]);
        dir = r.stdout.trim();
      } catch (err) {
        console.error(`[api] fs/list cwd failed: ${err.message}`);
        return sendJson(res, 502, { error: "failed to resolve session cwd" });
      }
    }
    if (!isAbsPath(dir)) {
      return sendJson(res, 400, { error: "path must be an absolute path" });
    }
    const showHidden = ["1", "true", "yes"].includes(
      String(url.searchParams.get("showHidden") || "").toLowerCase(),
    );

    // Confirm it's a directory so listing a file doesn't look like an empty dir.
    try {
      const ty = await fsStatType(server, dir);
      if (ty !== "d") {
        return sendJson(res, 404, { error: "not a directory" });
      }
    } catch (err) {
      return sendJson(res, fsErrorStatus(err), {
        error: fsErrorMessage(err, "cannot access path"),
      });
    }

    const findArgs = ["find", dir, "-maxdepth", "1", "-mindepth", "1"];
    if (!showHidden) findArgs.push("!", "-name", ".*");
    // Fields tab-delimited; records NUL-delimited so spaces/tabs/newlines in
    // names can't corrupt parsing. find interprets the \t and \0 escapes.
    findArgs.push("-printf", "%y\\t%s\\t%T@\\t%m\\t%l\\t%f\\0");

    let out;
    try {
      out = await serverCmd(server, findArgs);
    } catch (err) {
      return sendJson(res, fsErrorStatus(err), {
        error: fsErrorMessage(err, "failed to list directory"),
      });
    }

    const records = out.stdout.split("\0").filter((r) => r.length > 0);
    let truncated = false;
    let usable = records;
    if (records.length > FS_LIST_CAP) {
      usable = records.slice(0, FS_LIST_CAP);
      truncated = true;
    }
    const entries = [];
    for (const rec of usable) {
      const f = rec.split("\t");
      if (f.length < 6) continue;
      const type = fsTypeOf(f[0]);
      const mtimeSec = parseFloat(f[2]);
      const mtime = Number.isFinite(mtimeSec)
        ? Math.round(mtimeSec * 1000)
        : null;
      // %f is last; slice(5) reconstructs a name containing a literal tab.
      const name = f.slice(5).join("\t");
      const entry = {
        name,
        type,
        size: Number(f[1]) || 0,
        mtime,
        mode: f[3],
      };
      if (type === "symlink" && f[4]) entry.symlinkTarget = f[4];
      entries.push(entry);
    }
    const body = { path: dir, entries };
    if (truncated) body.truncated = true;
    return sendJson(res, 200, body);
  }

  // GET /api/sessions/:id/fs/read?path=<abs>  (text preview, capped)
  if (
    req.method === "GET" &&
    parts.length === 5 &&
    parts[1] === "sessions" &&
    parts[3] === "fs" &&
    parts[4] === "read"
  ) {
    const s = await fsResolveSession(res, parts[2]);
    if (!s) return true;
    const { server } = s;
    const p = url.searchParams.get("path");
    if (!isAbsPath(p)) {
      return sendJson(res, 400, { error: "path must be an absolute path" });
    }

    // True size + type (reject directories with a clear error).
    let size = 0;
    try {
      const st = await serverCmd(server, [
        "find",
        p,
        "-maxdepth",
        "0",
        "-printf",
        "%y\\t%s",
      ]);
      const [ty, sz] = st.stdout.split("\t");
      if (ty === "d") {
        return sendJson(res, 400, { error: "path is a directory" });
      }
      size = Number(sz) || 0;
    } catch (err) {
      return sendJson(res, fsErrorStatus(err), {
        error: fsErrorMessage(err, "cannot access path"),
      });
    }

    // Read up to CAP+1 bytes so we can detect truncation exactly.
    let buf;
    try {
      const r = await serverCmd(
        server,
        ["head", "-c", String(FS_READ_CAP + 1), "--", p],
        { encoding: "buffer" },
      );
      buf = r.stdout;
    } catch (err) {
      return sendJson(res, fsErrorStatus(err), {
        error: fsErrorMessage(err, "failed to read file"),
      });
    }

    const binary = buf.includes(0);
    const truncated = buf.length > FS_READ_CAP;
    const bytes = truncated ? buf.subarray(0, FS_READ_CAP) : buf;
    if (binary) {
      // Contract: binary files return no content, so `truncated` is always
      // false (there is no capped-text notion to signal). Matches the
      // FsReadResponseSchema doc in shared-types.
      return sendJson(res, 200, {
        path: p,
        size,
        binary: true,
        truncated: false,
        encoding: null,
      });
    }
    return sendJson(res, 200, {
      path: p,
      size,
      binary: false,
      truncated,
      encoding: "utf-8",
      content: bytes.toString("utf-8"),
    });
  }

  // GET /api/sessions/:id/fs/download?path=<abs>  (binary-safe, streamed, no cap)
  if (
    req.method === "GET" &&
    parts.length === 5 &&
    parts[1] === "sessions" &&
    parts[3] === "fs" &&
    parts[4] === "download"
  ) {
    const s = await fsResolveSession(res, parts[2]);
    if (!s) return true;
    const { server } = s;
    const p = url.searchParams.get("path");
    if (!isAbsPath(p)) {
      return sendJson(res, 400, { error: "path must be an absolute path" });
    }
    // Verify existence/type BEFORE streaming so we can still send 404/403/400.
    try {
      const ty = await fsStatType(server, p);
      if (ty === "d") {
        return sendJson(res, 400, { error: "path is a directory" });
      }
    } catch (err) {
      return sendJson(res, fsErrorStatus(err), {
        error: fsErrorMessage(err, "cannot access path"),
      });
    }

    const base = path.basename(p) || "download";
    // ASCII fallback for Content-Disposition + RFC 5987 UTF-8 form.
    const asciiName = base.replace(/[^\x20-\x7e]/g, "_").replace(/["\\]/g, "_");
    const argv = serverCmdArgv(server, ["cat", "--", p]);
    const child = spawn(argv[0], argv.slice(1), { env: childEnvFor(server) });

    const killTimer = setTimeout(() => {
      try {
        child.kill("SIGKILL");
      } catch {}
    }, FS_DOWNLOAD_TIMEOUT_MS);

    child.stderr.on("data", () => {});
    child.on("error", (err) => {
      clearTimeout(killTimer);
      console.error(`[api] fs/download spawn error: ${err.message}`);
      if (!res.headersSent) {
        sendJson(res, 502, { error: "failed to stream file" });
      } else if (!res.writableEnded) {
        res.end();
      }
    });
    child.on("close", () => {
      clearTimeout(killTimer);
      if (!res.writableEnded) res.end();
    });
    res.on("close", () => {
      clearTimeout(killTimer);
      try {
        child.kill("SIGKILL");
      } catch {}
    });

    res.writeHead(200, {
      "content-type": "application/octet-stream",
      "content-disposition": `attachment; filename="${asciiName}"; filename*=UTF-8''${encodeURIComponent(base)}`,
    });
    child.stdout.pipe(res);
    return true;
  }

  // POST /api/sessions/:id/fs/upload?path=<abs-dest>  (raw body -> tee, streamed)
  if (
    req.method === "POST" &&
    parts.length === 5 &&
    parts[1] === "sessions" &&
    parts[3] === "fs" &&
    parts[4] === "upload"
  ) {
    const s = await fsResolveSession(res, parts[2]);
    if (!s) return true;
    const { server } = s;
    const p = url.searchParams.get("path");
    if (!isAbsPath(p)) {
      return sendJson(res, 400, { error: "path must be an absolute path" });
    }

    // ROUTE-LOCAL BODY_LIMIT BYPASS: read the raw body here (NOT via readBody,
    // which enforces the global 64 KB BODY_LIMIT) up to the separate upload cap.
    // The global BODY_LIMIT is untouched.
    let buf;
    try {
      buf = await new Promise((resolve, reject) => {
        const chunks = [];
        let total = 0;
        let over = false;
        const tooLarge = () => {
          const e = new Error("upload too large");
          e.code = "UPLOAD_TOO_LARGE";
          return e;
        };
        req.on("data", (c) => {
          total += c.length;
          if (total > FS_UPLOAD_CAP) {
            // Over the cap: drop what we buffered and keep DRAINING (discarding)
            // rather than destroying the socket now. Destroying mid-upload makes
            // a fetch/XHR client see ECONNRESET instead of the 413 — the client
            // is still streaming, so the response never reaches it. Draining to
            // `end` lets the client finish and read the 413. A generous hard
            // ceiling still bounds a client that keeps pushing far past the cap.
            if (!over) {
              over = true;
              chunks.length = 0;
            }
            if (total > FS_UPLOAD_CAP + 64 * 1024 * 1024) {
              req.destroy();
              reject(tooLarge());
            }
            return;
          }
          chunks.push(c);
        });
        req.on("end", () =>
          over ? reject(tooLarge()) : resolve(Buffer.concat(chunks)),
        );
        req.on("error", reject);
      });
    } catch (err) {
      if (err.code === "UPLOAD_TOO_LARGE") {
        return sendJson(res, 413, {
          error: `upload exceeds ${FS_UPLOAD_CAP} bytes`,
        });
      }
      return sendJson(res, 400, { error: "failed to read upload body" });
    }

    try {
      // tee writes the file portably; its echoed stdout is discarded.
      await serverCmdStdin(server, ["tee", "--", p], buf);
    } catch (err) {
      return sendJson(res, fsErrorStatus(err), {
        error: fsErrorMessage(err, "failed to write file"),
      });
    }
    return sendJson(res, 200, { path: p, size: buf.length });
  }

  // POST /api/sessions/:id/fs/mkdir   body: { path }
  if (
    req.method === "POST" &&
    parts.length === 5 &&
    parts[1] === "sessions" &&
    parts[3] === "fs" &&
    parts[4] === "mkdir"
  ) {
    const s = await fsResolveSession(res, parts[2]);
    if (!s) return true;
    const { server } = s;
    let body = {};
    try {
      const raw = await readBody(req);
      if (raw.trim()) body = JSON.parse(raw);
      if (body === null || typeof body !== "object" || Array.isArray(body)) {
        return sendJson(res, 400, { error: "body must be a JSON object" });
      }
    } catch (err) {
      if (err.code === "BODY_TOO_LARGE") {
        res.writeHead(413, {
          "content-type": "application/json; charset=utf-8",
        });
        res.end(JSON.stringify({ error: "request too large" }));
        return true;
      }
      return sendJson(res, 400, { error: "malformed JSON body" });
    }
    if (!isAbsPath(body.path)) {
      return sendJson(res, 400, { error: "path must be an absolute path" });
    }
    try {
      // No -p: fail-if-exists so a re-create is a clean 409.
      await serverCmd(server, ["mkdir", "--", body.path]);
    } catch (err) {
      return sendJson(res, fsErrorStatus(err), {
        error: fsErrorMessage(err, "failed to create directory"),
      });
    }
    return sendJson(res, 201, { path: body.path });
  }

  // PATCH /api/sessions/:id/fs/entry   body: { from, to, overwrite? }  (rename/move)
  if (
    req.method === "PATCH" &&
    parts.length === 5 &&
    parts[1] === "sessions" &&
    parts[3] === "fs" &&
    parts[4] === "entry"
  ) {
    const s = await fsResolveSession(res, parts[2]);
    if (!s) return true;
    const { server } = s;
    let body = {};
    try {
      const raw = await readBody(req);
      if (raw.trim()) body = JSON.parse(raw);
      if (body === null || typeof body !== "object" || Array.isArray(body)) {
        return sendJson(res, 400, { error: "body must be a JSON object" });
      }
    } catch (err) {
      if (err.code === "BODY_TOO_LARGE") {
        res.writeHead(413, {
          "content-type": "application/json; charset=utf-8",
        });
        res.end(JSON.stringify({ error: "request too large" }));
        return true;
      }
      return sendJson(res, 400, { error: "malformed JSON body" });
    }
    if (!isAbsPath(body.from) || !isAbsPath(body.to)) {
      return sendJson(res, 400, {
        error: "from and to must be absolute paths",
      });
    }
    const overwrite = body.overwrite === true;
    if (!overwrite) {
      // No-clobber: 409 if the destination already exists.
      let exists = false;
      try {
        await fsStatType(server, body.to);
        exists = true;
      } catch {
        exists = false;
      }
      if (exists) {
        return sendJson(res, 409, { error: "destination already exists" });
      }
    }
    try {
      await serverCmd(server, ["mv", "--", body.from, body.to]);
    } catch (err) {
      return sendJson(res, fsErrorStatus(err), {
        error: fsErrorMessage(err, "failed to move"),
      });
    }
    return sendJson(res, 200, { from: body.from, to: body.to });
  }

  // DELETE /api/sessions/:id/fs/entry?path=<abs>&recursive=0
  if (
    req.method === "DELETE" &&
    parts.length === 5 &&
    parts[1] === "sessions" &&
    parts[3] === "fs" &&
    parts[4] === "entry"
  ) {
    const s = await fsResolveSession(res, parts[2]);
    if (!s) return true;
    const { server } = s;
    const p = url.searchParams.get("path");
    if (!isAbsPath(p)) {
      return sendJson(res, 400, { error: "path must be an absolute path" });
    }
    const recursive = ["1", "true", "yes"].includes(
      String(url.searchParams.get("recursive") || "").toLowerCase(),
    );
    let ty;
    try {
      ty = await fsStatType(server, p);
    } catch (err) {
      return sendJson(res, fsErrorStatus(err), {
        error: fsErrorMessage(err, "cannot access path"),
      });
    }
    try {
      if (ty === "d") {
        if (recursive) {
          await serverCmd(server, ["rm", "-r", "--", p]);
        } else {
          // rmdir fails on a non-empty dir -> "Directory not empty" -> 409.
          await serverCmd(server, ["rmdir", "--", p]);
        }
      } else {
        await serverCmd(server, ["rm", "--", p]);
      }
    } catch (err) {
      return sendJson(res, fsErrorStatus(err), {
        error: fsErrorMessage(err, "failed to delete"),
      });
    }
    return sendJson(res, 200, { path: p });
  }

  // GET /api/sessions/:id/screen
  // Agent Chat: read-only PLAIN-TEXT screen capture (no ANSI — this feeds an
  // LLM, not a terminal) plus cursor/size/mode metadata in one response.
  // Auth required (handled above). GET is exempt from Origin check.
  if (
    req.method === "GET" &&
    parts.length === 4 &&
    parts[1] === "sessions" &&
    parts[3] === "screen"
  ) {
    const { serverId, tmuxName } = parseSessionRef(
      decodeURIComponent(parts[2]),
    );
    if (!ID_RE.test(tmuxName)) {
      return sendJson(res, 404, { error: "session not found" });
    }
    const server = registry.get(serverId);
    if (!server) {
      return sendJson(res, 404, { error: "session not found" });
    }
    if (!(await sessionExists(server, tmuxName))) {
      return sendJson(res, 404, { error: "session not found" });
    }
    // Parse history param: integer 0..2000, default 0 (visible screen only).
    const rawHistory = url.searchParams.get("history");
    let history = 0;
    if (rawHistory !== null) {
      const parsed = parseInt(rawHistory, 10);
      if (Number.isFinite(parsed)) {
        history = Math.min(2000, Math.max(0, parsed));
      }
      // If not a valid integer, fall back to default 0.
    }
    try {
      // -p: stdout  -J: join wrapped lines  (deliberately NO -e: plain text)
      // -S -<N>: include N lines of history above the visible screen
      const captureArgs = ["capture-pane", "-p", "-J"];
      if (history > 0) captureArgs.push("-S", `-${history}`);
      captureArgs.push("-t", tmuxName);
      const [capture, meta] = await Promise.all([
        serverExec(server, captureArgs),
        serverExec(server, [
          "display-message",
          "-p",
          "-t",
          tmuxName,
          "#{cursor_x} #{cursor_y} #{pane_width} #{pane_height} #{alternate_on} #{pane_current_command}",
        ]),
      ]);
      // First five fields are numeric/flag; the command name comes last so a
      // (rare) space in it can't shift the numeric fields.
      const fields = meta.stdout.trimEnd().split(" ");
      return sendJson(res, 200, {
        screen: capture.stdout,
        cursor: { x: Number(fields[0]) || 0, y: Number(fields[1]) || 0 },
        size: { cols: Number(fields[2]) || 0, rows: Number(fields[3]) || 0 },
        altScreen: fields[4] === "1",
        currentCommand: fields.slice(5).join(" "),
      });
    } catch (err) {
      console.error(`[api] screen failed: ${err.message}`);
      return sendJson(res, 500, { error: "failed to capture screen" });
    }
  }

  // POST /api/sessions/:id/keys
  // Agent Chat: inject input into a session. Two body shapes (mirrors
  // SendKeysRequestSchema in @sparklab/shared-types):
  //   { text: string }   — typed LITERALLY, never executes (no implicit Enter)
  //   { keys: string[] } — whitelisted named keys (AGENT_NAMED_KEYS)
  // Origin check for POST already ran above. Never kills anything.
  if (
    req.method === "POST" &&
    parts.length === 4 &&
    parts[1] === "sessions" &&
    parts[3] === "keys"
  ) {
    const { serverId, tmuxName } = parseSessionRef(
      decodeURIComponent(parts[2]),
    );
    if (!ID_RE.test(tmuxName)) {
      return sendJson(res, 404, { error: "session not found" });
    }
    const server = registry.get(serverId);
    if (!server) {
      return sendJson(res, 404, { error: "session not found" });
    }
    if (!(await sessionExists(server, tmuxName))) {
      return sendJson(res, 404, { error: "session not found" });
    }
    let body = {};
    try {
      const raw = await readBody(req);
      if (raw.trim()) body = JSON.parse(raw);
      if (body === null || typeof body !== "object" || Array.isArray(body)) {
        return sendJson(res, 400, { error: "body must be a JSON object" });
      }
    } catch (err) {
      if (err.code === "BODY_TOO_LARGE") {
        res.writeHead(413, {
          "content-type": "application/json; charset=utf-8",
        });
        res.end(JSON.stringify({ error: "request too large" }));
        return true;
      }
      return sendJson(res, 400, { error: "malformed JSON body" });
    }

    const hasText = body.text !== undefined;
    const hasKeys = body.keys !== undefined;
    if (hasText === hasKeys) {
      return sendJson(res, 400, {
        error: "body must have exactly one of: text, keys",
      });
    }

    if (hasText) {
      if (typeof body.text !== "string") {
        return sendJson(res, 400, { error: "text must be a string" });
      }
      if (body.text.length < 1 || body.text.length > SEND_TEXT_MAX) {
        return sendJson(res, 400, {
          error: `text must be 1..${SEND_TEXT_MAX} characters`,
        });
      }
      const text = body.text;
      const singleLine = !text.includes("\n") && !text.includes("\r");
      try {
        if (singleLine && text.length <= SEND_KEYS_LITERAL_MAX) {
          // -l: literal (no key-name lookup); -- guards a leading "-" in text.
          await serverExec(server, [
            "send-keys",
            "-t",
            tmuxName,
            "-l",
            "--",
            text,
          ]);
        } else {
          // Long/multiline text: stage in a tmux buffer and bracketed-paste it
          // (-p), so a shell/editor receives it as a paste, not as typed
          // commands — newlines inside the paste never execute.
          const buf = `gw-agent-${crypto.randomUUID()}`;
          await serverExecStdin(server, ["load-buffer", "-b", buf, "-"], text);
          // -d deletes the buffer after pasting.
          await serverExec(server, [
            "paste-buffer",
            "-d",
            "-p",
            "-b",
            buf,
            "-t",
            tmuxName,
          ]);
        }
      } catch (err) {
        console.error(`[api] keys(text) failed: ${err.message}`);
        return sendJson(res, 500, { error: "failed to send text" });
      }
      res.writeHead(204);
      res.end();
      return true;
    }

    // keys variant
    if (
      !Array.isArray(body.keys) ||
      body.keys.length < 1 ||
      body.keys.length > 32
    ) {
      return sendJson(res, 400, { error: "keys must be an array of 1..32" });
    }
    for (const key of body.keys) {
      if (typeof key !== "string" || !AGENT_NAMED_KEYS.has(key)) {
        return sendJson(res, 400, { error: `unsupported key: ${String(key)}` });
      }
    }
    try {
      // No -l: these are tmux key names. Every item passed the whitelist.
      await serverExec(server, ["send-keys", "-t", tmuxName, ...body.keys]);
    } catch (err) {
      console.error(`[api] keys(keys) failed: ${err.message}`);
      return sendJson(res, 500, { error: "failed to send keys" });
    }
    res.writeHead(204);
    res.end();
    return true;
  }

  // PATCH /api/sessions/:id — metadata-only update (name, org, project).
  // Never touches tmux; safe on a live attached session.
  if (req.method === "PATCH" && parts.length === 3 && parts[1] === "sessions") {
    const { serverId, tmuxName } = parseSessionRef(
      decodeURIComponent(parts[2]),
    );
    if (!ID_RE.test(tmuxName)) {
      return sendJson(res, 400, { error: "invalid session id" });
    }
    const server = registry.get(serverId);
    if (!server) {
      return sendJson(res, 404, { error: "session not found" });
    }
    const id = formatSessionRef(serverId, tmuxName);
    if (!(await sessionExists(server, tmuxName))) {
      return sendJson(res, 404, { error: "session not found" });
    }
    let body = {};
    try {
      const raw = await readBody(req);
      if (raw.trim()) body = JSON.parse(raw);
      if (body === null || typeof body !== "object" || Array.isArray(body)) {
        return sendJson(res, 400, { error: "body must be a JSON object" });
      }
    } catch (err) {
      if (err.code === "BODY_TOO_LARGE") {
        res.writeHead(413, {
          "content-type": "application/json; charset=utf-8",
        });
        res.end(JSON.stringify({ error: "request too large" }));
        return true;
      }
      return sendJson(res, 400, { error: "malformed JSON body" });
    }

    const existing = metadata.get(id) || {};
    const patch = {};

    // Name
    if (body.name !== undefined) {
      if (typeof body.name !== "string") {
        return sendJson(res, 400, { error: "name must be a string" });
      }
      patch.name = body.name.trim() || existing.name || tmuxName;
    }

    // Org
    let mergedOrg = existing.org ?? null;
    if (body.org !== undefined) {
      if (body.org === null) {
        // Clearing org clears project too.
        patch.org = null;
        patch.project = null;
        mergedOrg = null;
      } else {
        const v = validateGroupField(body.org, "org");
        if (!v.ok) return sendJson(res, 400, { error: v.error });
        patch.org = v.value;
        mergedOrg = v.value;
      }
    }

    // Project
    let mergedProject =
      patch.project !== undefined ? patch.project : (existing.project ?? null);
    if (body.project !== undefined && patch.project === undefined) {
      // Only process if we didn't already force-clear project via org:null above.
      if (body.project === null) {
        patch.project = null;
        mergedProject = null;
      } else {
        const v = validateGroupField(body.project, "project");
        if (!v.ok) return sendJson(res, 400, { error: v.error });
        patch.project = v.value;
        mergedProject = v.value;
      }
    }

    // Invariant: project requires org (on the merged result).
    if (mergedProject && !mergedOrg) {
      return sendJson(res, 400, { error: "project requires org" });
    }

    metadata.upsert(id, patch);

    const updated = metadata.get(id) || {};
    return sendJson(res, 200, {
      id,
      name: updated.name || tmuxName,
      org: updated.org ?? null,
      project: updated.project ?? null,
    });
  }

  // DELETE /api/sessions/:id
  if (
    req.method === "DELETE" &&
    parts.length === 3 &&
    parts[1] === "sessions"
  ) {
    const { serverId, tmuxName } = parseSessionRef(
      decodeURIComponent(parts[2]),
    );
    if (!ID_RE.test(tmuxName)) {
      return sendJson(res, 400, { error: "invalid session id" });
    }
    const server = registry.get(serverId);
    if (!server) {
      return sendJson(res, 404, { error: "session not found" });
    }
    const id = formatSessionRef(serverId, tmuxName);
    if (!(await sessionExists(server, tmuxName))) {
      return sendJson(res, 404, { error: "session not found" });
    }
    try {
      // THE ONE INTENTIONAL KILL. This is the only place the gateway terminates
      // a tmux session; it actually kills the running job, so the UI confirms
      // first. Everywhere else we only detach (pty.kill).
      await serverExec(server, ["kill-session", "-t", tmuxName]);
    } catch (err) {
      console.error(`[api] delete failed: ${err.message}`);
      return sendJson(res, 500, { error: "failed to kill session" });
    }
    metadata.remove(id);
    console.log(`[api] deleted session "${id}"`);
    res.writeHead(204);
    res.end();
    return true;
  }

  // Unknown /api/* route.
  sendJson(res, 404, { error: "not found" });
  return true;
}

// ---- Static file serving ----
function serveStatic(req, res) {
  const url = new URL(req.url, `http://${req.headers.host}`);
  let pathname = decodeURIComponent(url.pathname);
  if (pathname === "/") pathname = "/index.html";

  const filePath = path.join(PUBLIC_DIR, pathname);
  // Prevent path traversal outside PUBLIC_DIR.
  if (!filePath.startsWith(PUBLIC_DIR)) {
    res.writeHead(403);
    res.end("Forbidden");
    return;
  }

  fs.readFile(filePath, (err, data) => {
    if (err) {
      res.writeHead(404, { "content-type": "text/plain" });
      res.end("Not found");
      return;
    }
    const ext = path.extname(filePath).toLowerCase();
    res.writeHead(200, {
      "content-type": MIME[ext] || "application/octet-stream",
    });
    res.end(data);
  });
}

const server = http.createServer((req, res) => {
  const url = new URL(req.url, `http://${req.headers.host}`);
  // Route /api/* before static.
  if (url.pathname === "/api" || url.pathname.startsWith("/api/")) {
    handleApi(req, res, url).catch((err) => {
      console.error(`[api] unhandled: ${err.stack || err}`);
      if (!res.headersSent) sendJson(res, 500, { error: "internal error" });
    });
    return;
  }
  serveStatic(req, res);
});

// A4: Slow-loris / timeout guards.
server.headersTimeout = 30_000;
server.requestTimeout = 60_000;

// ---- WebSocket attach endpoint ----
const wss = new WebSocketServer({ noServer: true });

server.on("upgrade", (req, socket, head) => {
  const url = new URL(req.url, `http://${req.headers.host}`);
  if (url.pathname !== "/attach") {
    socket.destroy();
    return;
  }
  // A1: Origin check BEFORE handshake (CSWSH guard).
  // In open mode this is skipped so non-browser clients (test scripts, curl) work.
  const origin = req.headers.origin;
  if (!isOriginAllowed(origin)) {
    socket.write(
      "HTTP/1.1 403 Forbidden\r\nContent-Length: 0\r\nConnection: close\r\n\r\n",
    );
    socket.destroy();
    return;
  }
  wss.handleUpgrade(req, socket, head, (ws) => {
    wss.emit("connection", ws, req);
  });
});

wss.on("connection", async (ws, req) => {
  // A2: Auth check post-handshake (upgrade already completed).
  // Close code 4001 is contractual — the frontend maps it to no-reconnect.
  if (!isAuthenticated(req)) {
    if (ws.readyState === ws.OPEN) {
      ws.send(JSON.stringify({ type: "error", message: "unauthorized" }));
    }
    ws.close(4001, "unauthorized");
    return;
  }

  // A4: Connection cap — over-cap connections are rejected post-handshake.
  // wss.clients already includes this new connection, so > MAX means we just exceeded it.
  if (wss.clients.size > MAX_WS_CONNECTIONS) {
    if (ws.readyState === ws.OPEN) {
      ws.send(
        JSON.stringify({ type: "error", message: "too many connections" }),
      );
    }
    ws.close(1013);
    return;
  }

  const url = new URL(req.url, `http://${req.headers.host}`);
  // The `session` param carries the QUALIFIED id (`<serverId>/web-<uuid>`);
  // encodeURIComponent on the client turns "/" into "%2F", which searchParams
  // decodes back cleanly. A bare `web-<uuid>` (old client) => serverId "local".
  const sessionRef = url.searchParams.get("session") || "";
  const { serverId, tmuxName } = parseSessionRef(sessionRef);

  // Attach only ever attaches to an EXISTING web- session. It never creates.
  // A bad prefix or missing session is a client error, not a reason to spawn a
  // new tmux session (that would bypass POST and leak sessions on typos).
  if (!ID_RE.test(tmuxName)) {
    if (ws.readyState === ws.OPEN) {
      ws.send(
        JSON.stringify({
          type: "error",
          message: `invalid session id "${sessionRef}"`,
        }),
      );
    }
    ws.close();
    return;
  }
  const server = registry.get(serverId);
  if (!server) {
    if (ws.readyState === ws.OPEN) {
      ws.send(
        JSON.stringify({
          type: "error",
          message: `unknown server "${serverId}"`,
        }),
      );
    }
    ws.close();
    return;
  }
  if (!(await sessionExists(server, tmuxName))) {
    if (ws.readyState === ws.OPEN) {
      ws.send(
        JSON.stringify({
          type: "error",
          message: `session "${sessionRef}" does not exist`,
        }),
      );
    }
    ws.close();
    return;
  }

  // Spawn the pty that attaches to tmux. encoding: null => onData yields raw
  // Buffers, so multibyte UTF-8 is never decoded/corrupted mid-pipeline. For an
  // ssh server this becomes `ssh -tt <host> tmux attach-session …` (the SECOND
  // exec seam) — node-pty gives ssh a pty so the remote attach gets a tty.
  const attachArgv = serverExecArgv(
    server,
    ["attach-session", "-t", tmuxName],
    { tty: true },
  );
  let pty;
  try {
    pty = ptySpawn(attachArgv[0], attachArgv.slice(1), {
      name: "xterm-256color",
      cols: 80,
      rows: 24,
      encoding: null,
      env: childEnvFor(server),
    });
  } catch (err) {
    if (ws.readyState === ws.OPEN) {
      ws.send(
        JSON.stringify({
          type: "error",
          message: `failed to attach: ${err.message}`,
        }),
      );
    }
    ws.close();
    return;
  }
  console.log(
    `[attach] session="${formatSessionRef(serverId, tmuxName)}" pty=${pty.pid} client attached`,
  );

  let torndown = false;
  const teardown = (why) => {
    if (torndown) return;
    torndown = true;
    // The ONLY kill on disconnect: our own pty (detaches the tmux client).
    // We NEVER kill the tmux session — that is what keeps jobs alive.
    try {
      pty.kill();
    } catch {}
    console.log(
      `[teardown] session="${formatSessionRef(serverId, tmuxName)}" pty=${pty.pid} killed (${why}); tmux session left running`,
    );
  };

  // pty output -> WS as BINARY frames.
  const onData = pty.onData((data) => {
    if (ws.readyState !== ws.OPEN) return;
    ws.send(Buffer.isBuffer(data) ? data : Buffer.from(data), { binary: true });
  });

  // If the shell inside the session exits, the attach pty exits too.
  const onExit = pty.onExit(({ exitCode }) => {
    if (ws.readyState === ws.OPEN) {
      ws.send(JSON.stringify({ type: "exit", code: exitCode }));
      ws.close();
    }
  });

  ws.on("message", (data, isBinary) => {
    if (isBinary) {
      // Keystrokes: pipe straight into the pty.
      pty.write(data);
      return;
    }
    // Text frame: JSON control message.
    let msg;
    try {
      msg = JSON.parse(data.toString("utf8"));
    } catch {
      return;
    }
    if (
      msg.type === "resize" &&
      Number.isFinite(msg.cols) &&
      Number.isFinite(msg.rows)
    ) {
      try {
        pty.resize(msg.cols, msg.rows);
      } catch {}
    } else if (msg.type === "ping") {
      if (ws.readyState === ws.OPEN) ws.send(JSON.stringify({ type: "pong" }));
    }
  });

  ws.on("close", () => {
    onData.dispose();
    onExit.dispose();
    teardown("ws close");
  });
  ws.on("error", (err) => {
    onData.dispose();
    onExit.dispose();
    teardown(`ws error: ${err.message}`);
  });
});

// A3: Bind to HOST (default 127.0.0.1).
server.listen(PORT, HOST, () => {
  console.log(`web-terminal gateway listening on http://${HOST}:${PORT}`);
  // If subscriptions persisted across a restart AND VAPID is configured, boot
  // the poll loop now (its first tick re-baselines and notifies nothing).
  if (push.isConfigured() && push.count() > 0) {
    startPushLoop();
    console.log(
      `[push] ${push.count()} persisted subscription(s); loop active.`,
    );
  }
});
